# QUESTÃO 1

In [1]:
import numpy as np
import sympy as sp

In [2]:
x = sp.symbols('x')

expr = (x**2-2*x)/(sp.cos(x))

In [3]:
def f(x):
    return (x**2-2*x)/np.cos(x)

# RESPOSTAS 1

In [4]:
# 1a
print("usando numpy: ", f(1))
print("usando sympy: ", expr.subs(x,1).evalf())

usando numpy:  -1.850815717680926
usando sympy:  -1.85081571768093


In [5]:
# 1b
print(sp.limit(expr,x,9).evalf())

-69.1448880972126


In [6]:
# 1c
print(sp.diff(expr,x))

(2*x - 2)/cos(x) + (x**2 - 2*x)*sin(x)/cos(x)**2


# QUESTÃO 2

In [7]:
A = np.array([[1,0,1],[1,2,3],[1,2,4]])
B = np.array([[3,1,4],[1,2,1],[3,1,1]])

# RESPOSTAS 2

In [8]:
# 2a
det_A = np.linalg.det(A)
print(det_A)

2.0


In [9]:
# 2b
inv_B = np.linalg.inv(B)
print(inv_B)

[[-0.06666667 -0.2         0.46666667]
 [-0.13333333  0.6        -0.06666667]
 [ 0.33333333 -0.         -0.33333333]]


In [10]:
# 2c
t_A = A.T
print(t_A)

[[1 1 1]
 [0 2 2]
 [1 3 4]]


In [11]:
# 2d
AB = np.dot(A,B)
print(AB)

[[ 6  2  5]
 [14  8  9]
 [17  9 10]]


In [12]:
# 2e
mult = A-(4*B)
print(mult)

[[-11  -4 -15]
 [ -3  -6  -1]
 [-11  -2   0]]
